import { Biomarker, CollectionMethod } from './types/index'

export const hardcoded_collection_methods: CollectionMethod[] = [
  'testkit',
  'at_home_phlebotomy',
]
export const mapCollectionMethods: Record<CollectionMethod, string> = {
  testkit: 'Test Kit',
  at_home_phlebotomy: 'At Home Phlebotomy',
  walk_in_test: 'Walk In Test',
}

export const local_biomarkers: Biomarker[] = [
  {
    id: 5265,
    name: '17-Hydroxyprogesterone Response to ACTH Stimulation',
    slug: '17-hydroxyprogesterone-response-to-acth-stimulation',
    description: '17-Hydroxyprogesterone Response to ACTH Stimulation',
    lab_id: 4,
    provider_id: '17682',
    type: 'panel',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 17028,
        name: '17 Hydroxyprogesterone, Baseline',
        slug: '17-hydroxyprogesterone-baseline',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 18188,
          name: '17-Hydroxyprogesterone baseline [Mass/Vol]',
          slug: '17-hydroxyprogesterone-baseline-mass-vol',
          code: '27996-8',
          unit: 'ng/dL',
        },
      },
      {
        id: 17029,
        name: '17 Hydroxyprogesterone, 60 Minutes',
        slug: '17-hydroxyprogesterone-60-minutes',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 5791,
          name: '17-Hydroxyprogesterone 1 Hr post 250 ug corticotropin IM [Mass/Vol]',
          slug: '17-hydroxyprogesterone-1-hr-post-250-ug-corticotropin-im-mass-vol',
          code: '14114-3',
          unit: 'ng/dL',
        },
      },
    ],
  },
  {
    id: 3010,
    name: '25-(OH) Vitamin D',
    slug: 'vitd',
    description: 'Marker',
    lab_id: 3,
    provider_id: null,
    type: 'biomarker',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 6672,
        name: '25-(OH) Vitamin D',
        slug: 'vitd',
        lab_id: 3,
        provider_id: null,
        loinc: {
          id: 43959,
          name: '25-hydroxyvitamin D [Mass/Vol]',
          slug: '25-hydroxyvitamin-d-mass-vol',
          code: '62292-8',
          unit: 'ng/mL',
        },
      },
    ],
  },
  {
    id: 5385,
    name: 'ABL Kinase Domain Mutation in CML, Cell-based',
    slug: 'abl-kinase-domain-mutation-in-cml-cell-based',
    description: 'ABL Kinase Domain Mutation in CML, Cell-based',
    lab_id: 4,
    provider_id: '16029',
    type: 'panel',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 17509,
        name: 'Abl Mutation, Cell Based',
        slug: 'abl-mutation-cell-based',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 38459,
          name: 'BCR-ABL1 kinase domain targeted mutation analysis Molgen Nom (Bld/Tiss)',
          slug: 'bcr-abl1-kinase-domain-targeted-mutation-analysis-molgen-nom-bld-tiss',
          code: '55135-8',
          unit: null,
        },
      },
      {
        id: 17510,
        name: 'Abl Possible Mutations',
        slug: 'abl-possible-mutations',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 38459,
          name: 'BCR-ABL1 kinase domain targeted mutation analysis Molgen Nom (Bld/Tiss)',
          slug: 'bcr-abl1-kinase-domain-targeted-mutation-analysis-molgen-nom-bld-tiss',
          code: '55135-8',
          unit: null,
        },
      },
    ],
  },
  {
    id: 5448,
    name: 'Acacia (t19) IgE',
    slug: 'acacia-t19-ige',
    description: 'Acacia (t19) IgE',
    lab_id: 4,
    provider_id: '2519',
    type: 'panel',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 17716,
        name: 'Acacia (T19) Ige',
        slug: 'acacia-t19-ige',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 42908,
          name: 'Wattle IgE Qn (S)',
          slug: 'wattle-ige-qn-s',
          code: '6015-2',
          unit: 'k[IU]/L',
        },
      },
      {
        id: 17717,
        name: 'Class',
        slug: 'class',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 1283,
          name: 'Wattle IgE RAST (S) [Presence]',
          slug: 'wattle-ige-rast-s-presence',
          code: '102126-0',
          unit: null,
        },
      },
    ],
  },
  {
    id: 3061,
    name: '17-Hydroxyprogesterone',
    slug: '17-hydroxyprogesterone',
    description: '17-Hydroxyprogesterone',
    lab_id: 4,
    provider_id: '17180',
    type: 'biomarker',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 6738,
        name: '17 Hydroxyprogesterone',
        slug: '17-hydroxyprogesterone',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 8560,
          name: '17-Hydroxyprogesterone [Mass/Vol]',
          slug: '17-hydroxyprogesterone-mass-vol',
          code: '1668-3',
          unit: 'ng/dL',
        },
      },
    ],
  },
  {
    id: 3131,
    name: 'ABO Group and Rh Type',
    slug: 'abo-group-and-rh-type',
    description: 'ABO Group and Rh Type',
    lab_id: 4,
    provider_id: '7788',
    type: 'panel',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 7048,
        name: 'Abo Group',
        slug: 'abo-group',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 55945,
          name: 'ABO group (Bld)',
          slug: 'abo-group-bld',
          code: '883-9',
          unit: null,
        },
      },
      {
        id: 7049,
        name: 'Rh Type',
        slug: 'rh-type',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 2395,
          name: 'Rh Nom (Bld)',
          slug: 'rh-nom-bld',
          code: '10331-7',
          unit: null,
        },
      },
    ],
  },
  {
    id: 3197,
    name: 'AccuType  CP, Clopidogrel CYP2C19 Genotype',
    slug: 'accutype-cp-clopidogrel-cyp2c19-genotype',
    description: 'AccuType  CP, Clopidogrel CYP2C19 Genotype',
    lab_id: 4,
    provider_id: '16924',
    type: 'biomarker',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 7296,
        name: 'Accutype(R) Cp, Clopidogrel Cyp2C19',
        slug: 'accutype-r-cp-clopidogrel-cyp2c19',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 40295,
          name: 'CYP2C19 gene allele genotype Molgen (Bld/Tiss)',
          slug: 'cyp2c19-gene-allele-genotype-molgen-bld-tiss',
          code: '57132-3',
          unit: null,
        },
      },
    ],
  },
  {
    id: 3330,
    name: 'AccuType  Warfarin',
    slug: 'accutype-warfarin',
    description: 'AccuType  Warfarin',
    lab_id: 4,
    provider_id: '16160',
    type: 'biomarker',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 7697,
        name: 'Accutype(R) Warfarin',
        slug: 'accutype-r-warfarin',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 38270,
          name: 'CYP2C9 and VKORC1 Molgen Nar (Bld/Tiss) [Interp]',
          slug: 'cyp2c9-and-vkorc1-molgen-nar-bld-tiss-interp',
          code: '54451-0',
          unit: null,
        },
      },
    ],
  },
  {
    id: 3487,
    name: '5-Hydroxyindoleacetic Acid (5-HIAA), Random Urine with Creatinine',
    slug: '5-hydroxyindoleacetic-acid-5-hiaa-random-urine-with-creatinine',
    description:
      '5-Hydroxyindoleacetic Acid (5-HIAA), Random Urine with Creatinine',
    lab_id: 4,
    provider_id: '1648',
    type: 'panel',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 8284,
        name: 'Creatinine, Random Urine',
        slug: 'creatinine-random-urine',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 12694,
          name: 'Creatinine (U) [Mass/Vol]',
          slug: 'creatinine-u-mass-vol',
          code: '2161-8',
          unit: 'mg/dL',
        },
      },
      {
        id: 8285,
        name: '5-Hiaa',
        slug: '5-hiaa',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 3296,
          name: '5-Hydroxyindoleacetate/Creatinine (U) [Mass ratio]',
          slug: '5-hydroxyindoleacetate-creatinine-u-mass-ratio',
          code: '11145-0',
          unit: 'mg/g{creat}',
        },
      },
    ],
  },
  {
    id: 3588,
    name: '1,5-Anhydroglucitol (1,5-AG), Intermediate Glycemic Control',
    slug: '15-anhydroglucitol-15-ag-intermediate-glycemic-control',
    description: '1,5-Anhydroglucitol (1,5-AG), Intermediate Glycemic Control',
    lab_id: 4,
    provider_id: '10378',
    type: 'biomarker',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 8678,
        name: '1,5 Ag, Intermediate Glycemic Control',
        slug: '15-ag-intermediate-glycemic-control',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 37626,
          name: '1,5-Anhydroglucitol [Mass/Vol]',
          slug: '15-anhydroglucitol-mass-vol',
          code: '53835-5',
          unit: 'ug/mL',
        },
      },
    ],
  },
  {
    id: 3646,
    name: '17-Hydroxyprogesterone Neonatal/Infant',
    slug: '17-hydroxyprogesterone-neonatal-infant',
    description: '17-Hydroxyprogesterone Neonatal/Infant',
    lab_id: 4,
    provider_id: '17654',
    type: 'biomarker',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 8840,
        name: '17 Hydroxyprogesterone, Neonatal/Infant',
        slug: '17-hydroxyprogesterone-neonatal-infant',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 8560,
          name: '17-Hydroxyprogesterone [Mass/Vol]',
          slug: '17-hydroxyprogesterone-mass-vol',
          code: '1668-3',
          unit: 'ng/dL',
        },
      },
    ],
  },
  {
    id: 3663,
    name: 'Acetaminophen',
    slug: 'acetaminophen',
    description: 'Acetaminophen',
    lab_id: 4,
    provider_id: '201',
    type: 'biomarker',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 8882,
        name: 'Acetaminophen',
        slug: 'acetaminophen',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 21935,
          name: 'Acetaminophen [Mass/Vol]',
          slug: 'acetaminophen-mass-vol',
          code: '3298-7',
          unit: 'ug/mL',
        },
      },
    ],
  },
  {
    id: 3805,
    name: 'Acetone',
    slug: 'acetone',
    description: 'Acetone',
    lab_id: 4,
    provider_id: '205',
    type: 'panel',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 9649,
        name: 'Acetone',
        slug: 'acetone',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 58335,
          name: 'Acetone (Bld) [Mass/Vol]',
          slug: 'acetone-bld-mass-vol',
          code: '9425-0',
          unit: 'mg/dL',
        },
      },
      {
        id: 9650,
        name: 'Volatile Analysis Performed On:',
        slug: 'volatile-analysis-performed-on',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 20208,
          name: 'Specimen source Nom (Specimen)',
          slug: 'specimen-source-nom-specimen',
          code: '31208-2',
          unit: null,
        },
      },
    ],
  },
  {
    id: 3922,
    name: '5-Hydroxyindoleacetic Acid (5-HIAA), 24-Hour Urine, with Creatinine',
    slug: '5-hydroxyindoleacetic-acid-5-hiaa-24-hour-urine-with-creatinine',
    description:
      '5-Hydroxyindoleacetic Acid (5-HIAA), 24-Hour Urine, with Creatinine',
    lab_id: 4,
    provider_id: '39625',
    type: 'panel',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 10658,
        name: 'Total Volume',
        slug: 'total-volume',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 20711,
          name: 'Specimen volume (24H U)',
          slug: 'specimen-volume-24h-u',
          code: '3167-4',
          unit: 'L',
        },
      },
      {
        id: 10659,
        name: '5-Hiaa, Urine',
        slug: '5-hiaa-urine',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 8852,
          name: '5-Hydroxyindoleacetate (24H U) [Mass/Time]',
          slug: '5-hydroxyindoleacetate-24h-u-mass-time',
          code: '1695-6',
          unit: 'mg/(24.h)',
        },
      },
      {
        id: 10660,
        name: 'Creatinine, Urine',
        slug: 'creatinine-urine',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 12703,
          name: 'Creatinine (24H U) [Mass/Time]',
          slug: 'creatinine-24h-u-mass-time',
          code: '2162-6',
          unit: 'g/(24.h)',
        },
      },
    ],
  },
  {
    id: 3925,
    name: 'Acetylcholinesterase',
    slug: 'acetylcholinesterase',
    description: 'Acetylcholinesterase',
    lab_id: 4,
    provider_id: '4929',
    type: 'panel',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 10677,
        name: 'Weeks Of Gestation',
        slug: 'weeks-of-gestation',
        lab_id: 4,
        provider_id: null,
        loinc: null,
      },
      {
        id: 10678,
        name: 'Acetylcholinesterase',
        slug: 'acetylcholinesterase',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 19357,
          name: 'Acetylcholinesterase Ql (Amn fld)',
          slug: 'acetylcholinesterase-ql-amn-fld',
          code: '30106-9',
          unit: null,
        },
      },
    ],
  },
  {
    id: 4265,
    name: 'ABO Group',
    slug: 'abo-group',
    description: 'ABO Group',
    lab_id: 4,
    provider_id: '785',
    type: 'biomarker',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 12379,
        name: 'Abo Group',
        slug: 'abo-group',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 55945,
          name: 'ABO group (Bld)',
          slug: 'abo-group-bld',
          code: '883-9',
          unit: null,
        },
      },
    ],
  },
  {
    id: 4415,
    name: '17-Hydroxypregnenolone',
    slug: '17-hydroxypregnenolone',
    description: '17-Hydroxypregnenolone',
    lab_id: 4,
    provider_id: '8352',
    type: 'biomarker',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 13057,
        name: '17 Hydroxypregnenolone',
        slug: '17-hydroxypregnenolone',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 45526,
          name: '17-Hydroxypregnenolone [Mass/Vol]',
          slug: '17-hydroxypregnenolone-mass-vol',
          code: '6765-2',
          unit: 'ng/dL',
        },
      },
    ],
  },
  {
    id: 4605,
    name: 'Acetylcholine Receptor Blocking Antibody',
    slug: 'acetylcholine-receptor-blocking-antibody',
    description: 'Acetylcholine Receptor Blocking Antibody',
    lab_id: 4,
    provider_id: '34459',
    type: 'biomarker',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 13890,
        name: 'Acetylcholine Receptor Blocking Antibody',
        slug: 'acetylcholine-receptor-blocking-antibody',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 3514,
          name: 'Acetylcholine receptor blocking Ab Qn (S)',
          slug: 'acetylcholine-receptor-blocking-ab-qn-s',
          code: '11561-8',
          unit: '%{inhibition}',
        },
      },
    ],
  },
  {
    id: 4647,
    name: 'Acetylcholine Receptor Ganglionic (Alpha 3) Antibody',
    slug: 'acetylcholine-receptor-ganglionic-alpha-3-antibody',
    description: 'Acetylcholine Receptor Ganglionic (Alpha 3) Antibody',
    lab_id: 4,
    provider_id: '93881',
    type: 'biomarker',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 14142,
        name: 'Acetylcholine Receptor Ganglionic (Alpha 3) Ab',
        slug: 'acetylcholine-receptor-ganglionic-alpha-3-ab',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 27954,
          name: 'Acetylcholine receptor ganglionic neuronal Ab (S) [Moles/Vol]',
          slug: 'acetylcholine-receptor-ganglionic-neuronal-ab-s-moles-vol',
          code: '42233-7',
          unit: 'nmol/mL',
        },
      },
    ],
  },
  {
    id: 4774,
    name: '3a-Androstanediol Glucuronide, ELISA',
    slug: '3a-androstanediol-glucuronide-elisa',
    description: '3a-Androstanediol Glucuronide, ELISA',
    lab_id: 4,
    provider_id: '92208',
    type: 'biomarker',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 14704,
        name: '3A Androstanediol Glucuronide, Elisa',
        slug: '3a-androstanediol-glucuronide-elisa',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 6781,
          name: '3-Alpha-Androstanediol glucuronide (S) [Moles/Vol]',
          slug: '3-alpha-androstanediol-glucuronide-s-moles-vol',
          code: '15008-6',
          unit: 'nmol/L',
        },
      },
    ],
  },
  {
    id: 5122,
    name: '19911A G Mutation Analysis',
    slug: '19911a-g-mutation-analysis',
    description: '19911A G Mutation Analysis',
    lab_id: 4,
    provider_id: '16533',
    type: 'biomarker',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 16448,
        name: '19911A>G Mutation Analysis',
        slug: '19911a-g-mutation-analysis',
        lab_id: 4,
        provider_id: null,
        loinc: null,
      },
    ],
  },
  {
    id: 5155,
    name: 'ABO Group and Rh Type, Cord Blood',
    slug: 'abo-group-and-rh-type-cord-blood',
    description: 'ABO Group and Rh Type, Cord Blood',
    lab_id: 4,
    provider_id: '19081',
    type: 'panel',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 16523,
        name: 'Abo Group',
        slug: 'abo-group',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 55945,
          name: 'ABO group (Bld)',
          slug: 'abo-group-bld',
          code: '883-9',
          unit: null,
        },
      },
      {
        id: 16524,
        name: 'Rh Type',
        slug: 'rh-type',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 2395,
          name: 'Rh Nom (Bld)',
          slug: 'rh-nom-bld',
          code: '10331-7',
          unit: null,
        },
      },
    ],
  },
  {
    id: 5166,
    name: 'Acarus siro (d70) IgE',
    slug: 'acarus-siro-d70-ige',
    description: 'Acarus siro (d70) IgE',
    lab_id: 4,
    provider_id: '23865',
    type: 'panel',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 16553,
        name: 'Acarus Siro (D70) Ige',
        slug: 'acarus-siro-d70-ige',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 44131,
          name: 'Acarus siro IgE Qn (S)',
          slug: 'acarus-siro-ige-qn-s',
          code: '6254-7',
          unit: 'k[IU]/L',
        },
      },
      {
        id: 16554,
        name: 'Class',
        slug: 'class',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 1792,
          name: 'Acarus siro IgE RAST (S) [Presence]',
          slug: 'acarus-siro-ige-rast-s-presence',
          code: '102611-1',
          unit: null,
        },
      },
    ],
  },
  {
    id: 5198,
    name: '11-Deoxycortisol',
    slug: '11-deoxycortisol',
    description: '11-Deoxycortisol',
    lab_id: 4,
    provider_id: '30543',
    type: 'biomarker',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 16610,
        name: '11 Deoxycortisol',
        slug: '11-deoxycortisol',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 8442,
          name: '11-Deoxycortisol [Mass/Vol]',
          slug: '11-deoxycortisol-mass-vol',
          code: '1657-6',
          unit: 'ng/dL;ug/mL',
        },
      },
    ],
  },
  {
    id: 5683,
    name: 'Abalone (f346) IgE',
    slug: 'abalone-f346-ige',
    description: 'Abalone (f346) IgE',
    lab_id: 4,
    provider_id: '38766',
    type: 'panel',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 19678,
        name: 'Abalone (F346) Ige',
        slug: 'abalone-f346-ige',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 46659,
          name: 'Abalone IgE Qn (S)',
          slug: 'abalone-ige-qn-s',
          code: '7060-7',
          unit: 'k[IU]/L',
        },
      },
      {
        id: 19679,
        name: 'Class',
        slug: 'class',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 1282,
          name: 'Abalone IgE RAST (S) [Presence]',
          slug: 'abalone-ige-rast-s-presence',
          code: '102125-2',
          unit: null,
        },
      },
    ],
  },
  {
    id: 5818,
    name: '3-Hydroxy-3-Methylglutaryl-Coenzyme A Reductase (HMGCR) Antibody (IgG)',
    slug: '3-hydroxy-3-methylglutaryl-coenzyme-a-reductase-hmgcr-antibody-igg',
    description:
      '3-Hydroxy-3-Methylglutaryl-Coenzyme A Reductase (HMGCR) Antibody (IgG)',
    lab_id: 4,
    provider_id: '39044',
    type: 'biomarker',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 20457,
        name: 'Hmgcr Ab (Igg)',
        slug: 'hmgcr-ab-igg',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 57838,
          name: '3-Hydroxy-3-Methylglutaryl-coenzyme A reductase IgG IA Qn (S)',
          slug: '3-hydroxy-3-methylglutaryl-coenzyme-a-reductase-igg-ia-qn-s',
          code: '93493-5',
          unit: '[IU]/mL',
        },
      },
    ],
  },
  {
    id: 6023,
    name: '5-Hydroxyindoleacetic Acid (5-HIAA), 24-Hour Urine without Creatinine',
    slug: '5-hydroxyindoleacetic-acid-5-hiaa-24-hour-urine-without-creatinine',
    description:
      '5-Hydroxyindoleacetic Acid (5-HIAA), 24-Hour Urine without Creatinine',
    lab_id: 4,
    provider_id: '523',
    type: 'panel',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 21712,
        name: 'Total Volume',
        slug: 'total-volume',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 20711,
          name: 'Specimen volume (24H U)',
          slug: 'specimen-volume-24h-u',
          code: '3167-4',
          unit: 'L',
        },
      },
      {
        id: 21713,
        name: '5 Hiaa, 24 Hour Urine',
        slug: '5-hiaa-24-hour-urine',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 8852,
          name: '5-Hydroxyindoleacetate (24H U) [Mass/Time]',
          slug: '5-hydroxyindoleacetate-24h-u-mass-time',
          code: '1695-6',
          unit: 'mg/(24.h)',
        },
      },
    ],
  },
  {
    id: 6043,
    name: '5 Nucleotidase',
    slug: '5-nucleotidase',
    description: '5 Nucleotidase',
    lab_id: 4,
    provider_id: '671',
    type: 'biomarker',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 21792,
        name: '5 Nucleotidase',
        slug: '5-nucleotidase',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 8799,
          name: '5-Nucleotidase [Catalytic activity/Vol]',
          slug: '5-nucleotidase-catalytic-activity-vol',
          code: '1690-7',
          unit: 'U/L',
        },
      },
    ],
  },
  {
    id: 6065,
    name: 'Absolute Lymphocyte Count',
    slug: 'absolute-lymphocyte-count',
    description: 'Absolute Lymphocyte Count',
    lab_id: 4,
    provider_id: '8561',
    type: 'panel',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 21893,
        name: 'White Blood Cell Count',
        slug: 'white-blood-cell-count',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 45430,
          name: 'WBC Auto (Bld) [#/Vol]',
          slug: 'wbc-auto-bld-vol',
          code: '6690-2',
          unit: '10*3/uL',
        },
      },
      {
        id: 21894,
        name: 'Lymphocytes',
        slug: 'lymphocytes',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 48615,
          name: 'Lymphocytes/100 WBC Auto (Bld)',
          slug: 'lymphocytes-100-wbc-auto-bld',
          code: '736-9',
          unit: '%',
        },
      },
      {
        id: 21895,
        name: 'Reactive Lymphocytes',
        slug: 'reactive-lymphocytes',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 4604,
          name: 'Variant lymphocytes/100 WBC (Bld)',
          slug: 'variant-lymphocytes-100-wbc-bld',
          code: '13046-8',
          unit: '%',
        },
      },
      {
        id: 21896,
        name: 'Absolute Lymphocytes',
        slug: 'absolute-lymphocytes',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 47964,
          name: 'Lymphocytes Auto (Bld) [#/Vol]',
          slug: 'lymphocytes-auto-bld-vol',
          code: '731-0',
          unit: '10*3/uL',
        },
      },
    ],
  },
  {
    id: 6071,
    name: 'AccuType  IL28B',
    slug: 'accutype-il28b',
    description: 'AccuType  IL28B',
    lab_id: 4,
    provider_id: '90251',
    type: 'panel',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 21932,
        name: 'Accutype(R) Il28B',
        slug: 'accutype-r-il28b',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 43045,
          name: 'IL28B gene associated variant rs12979860 Molgen Ql (Bld/Tiss)',
          slug: 'il28b-gene-associated-variant-rs12979860-molgen-ql-bld-tiss',
          code: '60279-7',
          unit: null,
        },
      },
      {
        id: 21933,
        name: 'Il28B Genotype:',
        slug: 'il28b-genotype',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 43045,
          name: 'IL28B gene associated variant rs12979860 Molgen Ql (Bld/Tiss)',
          slug: 'il28b-gene-associated-variant-rs12979860-molgen-ql-bld-tiss',
          code: '60279-7',
          unit: null,
        },
      },
    ],
  },
  {
    id: 193,
    name: 'Abdominal Fluid Cytology',
    slug: 'abdominal-fluid-cytology',
    description: 'Abdominal Fluid Cytology',
    lab_id: 6,
    provider_id: '009050',
    type: 'biomarker',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 215,
        name: '.',
        slug: '',
        lab_id: 6,
        provider_id: '019018',
        loinc: {
          id: 3500,
          name: 'Microscopic observation Other stain Nom (Specimen)',
          slug: 'microscopic-observation-other-stain-nom-specimen',
          code: '11546-9',
          unit: null,
        },
      },
      {
        id: 1022,
        name: 'DIAGNOSIS:',
        slug: 'diagnosis',
        lab_id: 6,
        provider_id: '191118',
        loinc: {
          id: 31737,
          name: 'Cytology report Cyto stain Doc (Specimen)',
          slug: 'cytology-report-cyto-stain-doc-specimen',
          code: '47526-9',
          unit: null,
        },
      },
    ],
  },
  {
    id: 194,
    name: 'Abnormal Bleeding Profile',
    slug: 'abnormal-bleeding-profile',
    description: 'Abnormal Bleeding Profile',
    lab_id: 6,
    provider_id: '116004',
    type: 'biomarker',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 297,
        name: 'PT',
        slug: 'pt',
        lab_id: 6,
        provider_id: '117030',
        loinc: {
          id: 41913,
          name: 'PT Coag (PPP) [Time]',
          slug: 'pt-coag-ppp-time',
          code: '5902-2',
          unit: 's',
        },
      },
      {
        id: 301,
        name: 'aPTT',
        slug: 'aptt',
        lab_id: 6,
        provider_id: '117012',
        loinc: {
          id: 6749,
          name: 'aPTT Coag (PPP) [Time]',
          slug: 'aptt-coag-ppp-time',
          code: '14979-9',
          unit: 's',
        },
      },
      {
        id: 305,
        name: 'INR',
        slug: 'inr',
        lab_id: 6,
        provider_id: '115108',
        loinc: {
          id: 44193,
          name: 'INR Coag (PPP) [Relative time]',
          slug: 'inr-coag-ppp-relative-time',
          code: '6301-6',
          unit: '{INR}',
        },
      },
      {
        id: 306,
        name: 'Thrombin Time',
        slug: 'thrombin-time',
        lab_id: 6,
        provider_id: '109009',
        loinc: {
          id: 21505,
          name: 'Thrombin time Coag (PPP) [Time]',
          slug: 'thrombin-time-coag-ppp-time',
          code: '3243-3',
          unit: 's',
        },
      },
      {
        id: 363,
        name: 'Platelets',
        slug: 'platelets',
        lab_id: 6,
        provider_id: '015172',
        loinc: {
          id: 51155,
          name: 'Platelets Auto (Bld) [#/Vol]',
          slug: 'platelets-auto-bld-vol',
          code: '777-3',
          unit: '10*3/uL',
        },
      },
    ],
  },
  {
    id: 195,
    name: 'ABO Grouping',
    slug: 'abo-grouping',
    description: 'ABO Grouping',
    lab_id: 6,
    provider_id: '006056',
    type: 'biomarker',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 1073,
        name: 'ABO Grouping',
        slug: 'abo-grouping',
        lab_id: 6,
        provider_id: '006056',
        loinc: {
          id: 55945,
          name: 'ABO group (Bld)',
          slug: 'abo-group-bld',
          code: '883-9',
          unit: null,
        },
      },
    ],
  },
  {
    id: 196,
    name: 'ABO Grouping and Rho(D) Typing',
    slug: 'abo-grouping-and-rho-d-typing',
    description: 'ABO Grouping and Rho(D) Typing',
    lab_id: 6,
    provider_id: '006049',
    type: 'biomarker',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 257,
        name: 'Rh Factor',
        slug: 'rh-factor',
        lab_id: 6,
        provider_id: '006064',
        loinc: {
          id: 2395,
          name: 'Rh Nom (Bld)',
          slug: 'rh-nom-bld',
          code: '10331-7',
          unit: null,
        },
      },
      {
        id: 1073,
        name: 'ABO Grouping',
        slug: 'abo-grouping',
        lab_id: 6,
        provider_id: '006056',
        loinc: {
          id: 55945,
          name: 'ABO group (Bld)',
          slug: 'abo-group-bld',
          code: '883-9',
          unit: null,
        },
      },
    ],
  },
  {
    id: 197,
    name: 'Acacia Gum',
    slug: 'acacia-gum',
    description: 'Acacia Gum',
    lab_id: 6,
    provider_id: '602851',
    type: 'biomarker',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 4568,
        name: 'F297-IgE Acacia Gum',
        slug: 'f297-ige-acacia-gum',
        lab_id: 6,
        provider_id: '602851',
        loinc: {
          id: 48694,
          name: 'Gum arabic IgE Qn (S)',
          slug: 'gum-arabic-ige-qn-s',
          code: '7382-5',
          unit: 'k[IU]/L',
        },
      },
    ],
  },
  {
    id: 198,
    name: 'Acarus Mite',
    slug: 'acarus-mite',
    description: 'Acarus Mite',
    lab_id: 6,
    provider_id: '602677',
    type: 'biomarker',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 4569,
        name: 'D070-IgE Acarus Mite',
        slug: 'd070-ige-acarus-mite',
        lab_id: 6,
        provider_id: '602677',
        loinc: {
          id: 44131,
          name: 'Acarus siro IgE Qn (S)',
          slug: 'acarus-siro-ige-qn-s',
          code: '6254-7',
          unit: 'k[IU]/L',
        },
      },
    ],
  },
  {
    id: 199,
    name: 'Acetaminophen',
    slug: 'acetaminophen',
    description: 'Acetaminophen',
    lab_id: 6,
    provider_id: '007740',
    type: 'biomarker',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 4570,
        name: 'Acetaminophen (Tylenol), S',
        slug: 'acetaminophen-tylenol-s',
        lab_id: 6,
        provider_id: '007745',
        loinc: {
          id: 21935,
          name: 'Acetaminophen [Mass/Vol]',
          slug: 'acetaminophen-mass-vol',
          code: '3298-7',
          unit: 'ug/mL',
        },
      },
    ],
  },
  {
    id: 200,
    name: 'Acetazolamide, Serum or Plasma',
    slug: 'acetazolamide-serum-or-plasma',
    description: 'Acetazolamide, Serum or Plasma',
    lab_id: 6,
    provider_id: '811984',
    type: 'biomarker',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 4571,
        name: 'Acetazolamide',
        slug: 'acetazolamide',
        lab_id: 6,
        provider_id: '808307',
        loinc: {
          id: 21943,
          name: 'acetaZOLAMIDE [Mass/Vol]',
          slug: 'acetazolamide-mass-vol',
          code: '3300-1',
          unit: 'ug/mL',
        },
      },
    ],
  },
  {
    id: 203,
    name: 'Acetylcholine Receptor (AChR) Antibodies, Complete Profile',
    slug: 'acetylcholine-receptor-achr-antibodies-complete-profile',
    description: 'Acetylcholine Receptor (AChR) Antibodies, Complete Profile',
    lab_id: 6,
    provider_id: '086020',
    type: 'biomarker',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 2938,
        name: 'AChR Blocking Abs, Serum',
        slug: 'achr-blocking-abs-serum',
        lab_id: 6,
        provider_id: '085927',
        loinc: {
          id: 3514,
          name: 'Acetylcholine receptor blocking Ab Qn (S)',
          slug: 'acetylcholine-receptor-blocking-ab-qn-s',
          code: '11561-8',
          unit: '%{inhibition}',
        },
      },
      {
        id: 2939,
        name: 'AChR Binding Abs, Serum',
        slug: 'achr-binding-abs-serum',
        lab_id: 6,
        provider_id: '085904',
        loinc: {
          id: 3174,
          name: 'Acetylcholine receptor binding Ab (S) [Moles/Vol]',
          slug: 'acetylcholine-receptor-binding-ab-s-moles-vol',
          code: '11034-6',
          unit: 'nmol/L',
        },
      },
      {
        id: 2940,
        name: 'AChR-modulating Ab',
        slug: 'achr-modulating-ab',
        lab_id: 6,
        provider_id: '505199',
        loinc: {
          id: 61121,
          name: 'Acetylcholine receptor modulation Ab FC Ql (S)',
          slug: 'acetylcholine-receptor-modulation-ab-fc-ql-s',
          code: '99062-2',
          unit: null,
        },
      },
    ],
  },
  {
    id: 202,
    name: 'Acetylcholine Receptor (AChR) Antibodies, Complete Profile with Reflex to MuSK Antibodies',
    slug: 'acetylcholine-receptor-achr-antibodies-complete-profile-with-reflex-to-musk-antibodies',
    description:
      'Acetylcholine Receptor (AChR) Antibodies, Complete Profile with Reflex to MuSK Antibodies',
    lab_id: 6,
    provider_id: '165605',
    type: 'biomarker',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 2938,
        name: 'AChR Blocking Abs, Serum',
        slug: 'achr-blocking-abs-serum',
        lab_id: 6,
        provider_id: '085927',
        loinc: {
          id: 3514,
          name: 'Acetylcholine receptor blocking Ab Qn (S)',
          slug: 'acetylcholine-receptor-blocking-ab-qn-s',
          code: '11561-8',
          unit: '%{inhibition}',
        },
      },
      {
        id: 2939,
        name: 'AChR Binding Abs, Serum',
        slug: 'achr-binding-abs-serum',
        lab_id: 6,
        provider_id: '085904',
        loinc: {
          id: 3174,
          name: 'Acetylcholine receptor binding Ab (S) [Moles/Vol]',
          slug: 'acetylcholine-receptor-binding-ab-s-moles-vol',
          code: '11034-6',
          unit: 'nmol/L',
        },
      },
      {
        id: 2940,
        name: 'AChR-modulating Ab',
        slug: 'achr-modulating-ab',
        lab_id: 6,
        provider_id: '505199',
        loinc: {
          id: 61121,
          name: 'Acetylcholine receptor modulation Ab FC Ql (S)',
          slug: 'acetylcholine-receptor-modulation-ab-fc-ql-s',
          code: '99062-2',
          unit: null,
        },
      },
    ],
  },
  {
    id: 205,
    name: 'Acetylcholine Receptor (AChR)-binding Antibodies',
    slug: 'acetylcholine-receptor-achr-binding-antibodies',
    description: 'Acetylcholine Receptor (AChR)-binding Antibodies',
    lab_id: 6,
    provider_id: '085902',
    type: 'biomarker',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 2939,
        name: 'AChR Binding Abs, Serum',
        slug: 'achr-binding-abs-serum',
        lab_id: 6,
        provider_id: '085904',
        loinc: {
          id: 3174,
          name: 'Acetylcholine receptor binding Ab (S) [Moles/Vol]',
          slug: 'acetylcholine-receptor-binding-ab-s-moles-vol',
          code: '11034-6',
          unit: 'nmol/L',
        },
      },
    ],
  },
  {
    id: 204,
    name: 'Acetylcholine Receptor (AChR) Binding Antibodies With Reflex to MuSK Antibodies',
    slug: 'acetylcholine-receptor-achr-binding-antibodies-with-reflex-to-musk-antibodies',
    description:
      'Acetylcholine Receptor (AChR) Binding Antibodies With Reflex to MuSK Antibodies',
    lab_id: 6,
    provider_id: '165592',
    type: 'biomarker',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 2939,
        name: 'AChR Binding Abs, Serum',
        slug: 'achr-binding-abs-serum',
        lab_id: 6,
        provider_id: '085904',
        loinc: {
          id: 3174,
          name: 'Acetylcholine receptor binding Ab (S) [Moles/Vol]',
          slug: 'acetylcholine-receptor-binding-ab-s-moles-vol',
          code: '11034-6',
          unit: 'nmol/L',
        },
      },
    ],
  },
  {
    id: 206,
    name: 'Acetylcholine Receptor (AChR)-blocking Antibodies',
    slug: 'acetylcholine-receptor-achr-blocking-antibodies',
    description: 'Acetylcholine Receptor (AChR)-blocking Antibodies',
    lab_id: 6,
    provider_id: '085926',
    type: 'biomarker',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 2938,
        name: 'AChR Blocking Abs, Serum',
        slug: 'achr-blocking-abs-serum',
        lab_id: 6,
        provider_id: '085927',
        loinc: {
          id: 3514,
          name: 'Acetylcholine receptor blocking Ab Qn (S)',
          slug: 'acetylcholine-receptor-blocking-ab-qn-s',
          code: '11561-8',
          unit: '%{inhibition}',
        },
      },
    ],
  },
  {
    id: 207,
    name: 'Acetylcholine Receptor (AChR)-modulating Antibodies, Flow Cytometry',
    slug: 'acetylcholine-receptor-achr-modulating-antibodies-flow-cytometry',
    description:
      'Acetylcholine Receptor (AChR)-modulating Antibodies, Flow Cytometry',
    lab_id: 6,
    provider_id: '505225',
    type: 'biomarker',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 2940,
        name: 'AChR-modulating Ab',
        slug: 'achr-modulating-ab',
        lab_id: 6,
        provider_id: '505199',
        loinc: {
          id: 61121,
          name: 'Acetylcholine receptor modulation Ab FC Ql (S)',
          slug: 'acetylcholine-receptor-modulation-ab-fc-ql-s',
          code: '99062-2',
          unit: null,
        },
      },
    ],
  },
  {
    id: 6341,
    name: '21- Hydroxylase Antibody',
    slug: '21-hydroxylase-antibody',
    description: '21- Hydroxylase Antibody',
    lab_id: 4,
    provider_id: '39226',
    type: 'biomarker',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 23368,
        name: '21 Hydroxylase Antibody',
        slug: '21-hydroxylase-antibody',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 54460,
          name: '21-Hydroxylase Ab Ql (S)',
          slug: '21-hydroxylase-ab-ql-s',
          code: '85363-0',
          unit: null,
        },
      },
    ],
  },
  {
    id: 6586,
    name: 'AccuType  Ribavirin (ITPA)',
    slug: 'accutype-ribavirin-itpa',
    description: 'AccuType  Ribavirin (ITPA)',
    lab_id: 4,
    provider_id: '91416',
    type: 'panel',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 24658,
        name: 'Rs1127354 Genotype',
        slug: 'rs1127354-genotype',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 56987,
          name: 'ITPA g.9330C>A Molgen Nom',
          slug: 'itpa-g-9330c-a-molgen-nom',
          code: '91137-0',
          unit: null,
        },
      },
      {
        id: 24659,
        name: 'Rs7270101 Genotype',
        slug: 'rs7270101-genotype',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 56988,
          name: 'ITPA g.9381A>C Molgen Nom',
          slug: 'itpa-g-9381a-c-molgen-nom',
          code: '91138-8',
          unit: null,
        },
      },
    ],
  },
  {
    id: 6646,
    name: '18-Hydroxycorticosterone',
    slug: '18-hydroxycorticosterone',
    description: '18-Hydroxycorticosterone',
    lab_id: 4,
    provider_id: '94621',
    type: 'biomarker',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 25141,
        name: '18 Hydroxycorticosterone',
        slug: '18-hydroxycorticosterone',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 8625,
          name: '18-Hydroxycorticosterone [Mass/Vol]',
          slug: '18-hydroxycorticosterone-mass-vol',
          code: '1674-1',
          unit: 'ng/dL',
        },
      },
    ],
  },
  {
    id: 6711,
    name: 'Acanthamoeba/Naegleria Culture',
    slug: 'acanthamoeba-naegleria-culture',
    description: 'Acanthamoeba/Naegleria Culture',
    lab_id: 4,
    provider_id: '23086',
    type: 'panel',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 25323,
        name: 'Source:',
        slug: 'source',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 20208,
          name: 'Specimen source Nom (Specimen)',
          slug: 'specimen-source-nom-specimen',
          code: '31208-2',
          unit: null,
        },
      },
      {
        id: 25324,
        name: 'Acanthamoeba/Naegleria Culture',
        slug: 'acanthamoeba-naegleria-culture',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 45186,
          name: 'Amoeba identified Org specific cx Nom (Specimen)',
          slug: 'amoeba-identified-org-specific-cx-nom-specimen',
          code: '6594-6',
          unit: null,
        },
      },
    ],
  },
  {
    id: 6781,
    name: 'Acetylcholine Receptor Binding Antibody',
    slug: 'acetylcholine-receptor-binding-antibody',
    description: 'Acetylcholine Receptor Binding Antibody',
    lab_id: 4,
    provider_id: '206',
    type: 'biomarker',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 25505,
        name: 'Acetylcholine Receptor Binding Antibody',
        slug: 'acetylcholine-receptor-binding-antibody',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 3174,
          name: 'Acetylcholine receptor binding Ab (S) [Moles/Vol]',
          slug: 'acetylcholine-receptor-binding-ab-s-moles-vol',
          code: '11034-6',
          unit: 'nmol/L',
        },
      },
    ],
  },
  {
    id: 6847,
    name: 'Acetylcholine Receptor Modulating Antibody',
    slug: 'acetylcholine-receptor-modulating-antibody',
    description: 'Acetylcholine Receptor Modulating Antibody',
    lab_id: 4,
    provider_id: '26474',
    type: 'biomarker',
    unit: null,
    price: 'N/A',
    expected_results: [
      {
        id: 25676,
        name: 'Acetylcholine Receptor Modulating Antibody',
        slug: 'acetylcholine-receptor-modulating-antibody',
        lab_id: 4,
        provider_id: null,
        loinc: {
          id: 3515,
          name: 'Acetylcholine receptor modulation Ab Qn (S)',
          slug: 'acetylcholine-receptor-modulation-ab-qn-s',
          code: '11562-6',
          unit: '[arbU]/mL',
        },
      },
    ],
  },
]
